headless.js
I think it is more consistent to use the interface instead of IP. it's more like in the GUI version and it's DHCP compatible.
=> Interface instead of IP and port

lib/device.js, lib/rest.js, public/index.html, public/userconfig.js
Also added system event listeners to selectively lockout devices, or lockout everything
=> Updated lockouts to be linkable

public/action.js, public/feedback.js, public/release_action.js
Fixes an issue where the action, release_action, and feedback tables could disappear due to an instance being disabled on startup or the action/feedback itself being undefined due to instance state.
=> Action & Feedback List Fix

documentation/raspberrypi.md
Adjusted clone commands for 1.3 and 1.4RC1 installation. Also added note for 1.4RC1 installation for the post-clone correction needed in tools/build_writefile.sh.
=> Updated raspberrypi.md

documentation/raspberrypi.md
adding recommendation to use Pi 4 2GB or 4GB instead of previous versions of the board
=> Minor: Update raspberrypi.md (#805) from jarodwsams

lib/elgato_dm.js
=> libusb update for linux on backport

public/index.html
Adds OSC Remote Control info next to the TCP/UDP Remote control
=> Patch: Add OSC Syntax to settings tab in app

lib/action.js, lib/device.js
Covers Issue #775 #745 #909
After this patch, an update to lib/module/bitfocus-companion will fix #938
=> Latch button and Page Change detect

lib/instance_skel.js
lint tool found mismatched parens.
Not sure if it actually affects anyone :)
=> Skel regex typo

lib/osc.js, lib/server_http.js
Fixed an issue where bgcolor, color, or text updates to a bank over OSC were emitting the wrong message to trigger graphical updates of buttons.
=> Fix: Corrected emit on OSC bank update

public/instance.js
When adding an instance, sort the category and manufacturer lists by name to make it easier to find things
=> Minor: Sort instance category/manufacturer lists by name

public/bank.js, public/import.js, public/index.css, public/index.html
Adds the ability to jump to a page using text input followed by the return key. This is implemented on both the button layout editor and import pages.
=> Feat: Jump to page

public/bank.js
Solves issue https://github.com/bitfocus/companion/issues/937
=> Minor: Fixes issue where cursor would jump to end of input

lib/bank.js, lib/image.js, lib/instance_skel.js, lib/server_http.js
Added a function to reverse the output from the rgb function.
As I mentioned in #1104
I have tested this myself and hopefully this pull request all works :)
=> rgbRev function

lib/instance_skel.d.ts, lib/instance_skel.js
@Julusian do you want to update the TS definitions for this PR?
=> Minor: add parseVariables in instance_skel

app.js, lib/preview.js, lib/schedule.js, lib/schedule/companion_instance.js, lib/schedule/interval.js, lib/schedule/plugin_base.js, lib/schedule/time_of_day.js, lib/schedule/variable.js, package.json, public/index.html, public/schedule.js
This adds a built in scheduler and trigger system that allows buttons to be pressed based on various things:
- Time of day
- Companion instance specific (button press, instance start, webpage load)
- Variable changes (use cases might be a slide is changed in ProPresenter, a media transport device plays a file, or an event is run on a switcher)
This will close #389. I tried making the scheduler where it can easily be expanded using a plugin architecture of sorts.
=> Major: System Scheduler and Trigger

lib/action.js
Core/internal listener for the `abort_one` action.
My pretty-formatter also stripped some trailing whitespace :)
=> Minor: 'abort_one' action

public/manifest.json
=> Allow PWA on all pages using manifest.json - remove start_url

lib/device.js, lib/elgato_dm.js, lib/usb/handler.js, lib/usb/xkeys.js, package.json, public/devices.js, yarn.lock
=> XK-80 support

lib/server_api.js, public/index.html
Amateur programmer and first actual pull request.
I needed to be able to style buttons over TCP so I added changing text and color/bgcolor.
I also noticed that the HTTP API had some un-documented features so I added those to the settings tab along the new things.
Let me know if there is anything I should change.
=> Added styling over TCP, updated settings tab info

public/index.html
Saw this issue and felt the same:
https://github.com/bitfocus/companion/issues/1338
Saves a click for each button made
=> Regular button as default type

lib/graphics.js, public/userconfig.js, webui/src/UserConfig.jsx
Implements the remove top bar feature in the new react UI.
There is also a change to update surfaces after the change has taken place. This prevents users needing to change page in order to see the updated look and eliminates the need to refresh web GUI.
=> feat: Implement 'remove top bar' setting in React UI

public/ipad.html
This PR adds an ipad.html, which is a modified version of tablet.html to make it fit on ipad screens which are 4x3. It also improves the visuals of the Next/Previous buttons.
=> feat: create ipad.html, optimized for use on iPad (4x3 screens)

webui/src/Buttons/ButtonGrid.jsx
Fixes https://github.com/bitfocus/companion/issues/1458
=> fix(webui): Safari de-selecting page number

public/js/preview.js, webui/src/Buttons/EditButton/ButtonStyleConfig.jsx, webui/src/Components/PNGInputField.jsx
Implements #1545 
PR includes changes to both legacy and React WebUI
=> feat: Resize uploaded button images to max dimensions when too large

lib/feedback.js
Adds the current button (page, bank) being processed to the module feedback function call.
Allows the module to see which button is being updated.
For @MeestorX
=> feat: Pass button being updated to feedback call

webui/src/UserConfig.jsx
Changes the "Remote Control" information area on the right side of the "Settings" tab to a tabbed interface.
=> feat: switch remote control info to tabs

instance_skel.d.ts
Added label to the instance type as it was missing.
=> chore: add label to instance definition

Dockerfile
Resolves https://github.com/bitfocus/companion/issues/1718
=> chore(docker): add cmake and remove empty continuation line

package.json, yarn.lock
Hi maintainers,
this is the first version of the MakeProX Glue module.
If there's anything else that needs to be done before this module can be added?
=> add makepro-x glue module v1.0.0

docs/5_remote_control/1_tcp_udp.md, docs/5_remote_control/2_http_remote_control.md, docs/5_remote_control/3_osc_control.md, lib/server_api.js, lib/server_http.js, lib/server_osc.js
This should make it easier to integrate with other systems, related to #1274 and #481.
=> feat: add rescan control to HTTP, TCP, UDP, OSC interfaces

electron.js, headless.js, package.json, yarn.lock
=> fix: show vlan interfaces in launcher

.github/workflows/nodejs.yml, electron.js, package.json, tools/build_sentry.mjs
Migrates sentry activation to official builds only via CI.
=> minor: integrate sentry via CI

instance_skel_types.d.ts
Minor typo fix to the type interface for the HTTP request update
=> Fix: http request types

tcp.js, telnet.js, udp.js
Fix incorrect test for listenerCount = 0
=> Fix: show error message when listenerCount is 0

docs/5_remote_control/http_remote_control.md
Had to do a bit of digging to find this one - Figured it might be handy.
=> Adding HTTP command examples to set the state of a button

lib/Instance/Controller.js, webui/src/Components/GenericConfirmModal.jsx, webui/src/Instances/AddInstance.jsx, webui/src/Instances/InstanceEditPanel.jsx, webui/src/Instances/InstanceList.jsx, webui/src/scss/_instances.scss
Instances list: 
Add instance list:
Confirmation when adding:
=> feat: identify legacy modules in ui

lib/Instance/Variable.js, lib/Internal/Controls.js, lib/Internal/CustomVariables.js, lib/Shared/Expression/ExpressionFunctions.js
Replaces some of the `Custom Variable: Modify Value with *` actions with suitable `Custom Variable: Set with expression` implementations.
Combines `Button: Trigger press and release if variable meets condition (Custom Variables)` into non custom variable version
=> feat: combine some internal actions

lib/Internal/Controls.js
Button: Set current step  if variable meets condition
=> feat: Set current step  if variable meets condition

lib/Instance/Variable.js
=> fix: variables not updated when equal but not same

docs/4_secondary_admin_controls/expressions/functions.md, lib/Shared/Expression/ExpressionFunctions.js
Adds the following string expressions
- includes
- toUpperCase
- toLowerCase
- replaceAll
=> feat: add additional string expressions

lib/Internal/CustomVariables.js
Allow user to create variables at runtime on a button.
My initial idea was that it would be possible to create internal variables for each button, to facilitate the logic and programming of each button individually.
As I'm still new to the Companion code structure, the way I found to convey my idea was this, I hope you like it and that perhaps one day we can evolve to internal variables per button.
=> feat: Set or Create raw value if not exists

lib/Data/Upgrades/v2tov3.js
(cherry picked from commit 64d5b8e8c2fdeb427dc94623cf46029f592aee85)
Given I'm pretty confident master crashes in the same way...
=> fix: crash with fresh config #2557

lib/Data/UserConfig.js
=> Spelling s/renewSslSertificate renewSslCertificate

docs/1_welcome.md, docs/3_config/buttons/feedbacks.md, docs/3_config/buttons/steps.md, docs/4_secondary_admin_controls/expressions/functions.md
=> Documentation spelling

lib/Graphics/Controller.js, lib/Graphics/Image.js
=> fix: canvas font selection #2647

launcher/main.js
https://bitfocusio.slack.com/archives/CFG7HAN5N/p1707670441992519
=> feature: filter the files watched in the launcher

docs/4_secondary_admin_controls/expressions/operators.md
For a long time I thought you didn't have a ternary operator because it wasn't listed here. And since I was in here adding it, I fixed a couple typos too.
I know, I know. If I had just read the things above this list, I would have realized it, but I'm a skimmer.
=> Fix typos and missing operators.

companion/lib/Instance/Host.js, companion/lib/Instance/Wrapper.js, companion/lib/Service/BonjourDiscovery.js, companion/lib/Service/Controller.js, companion/lib/Service/SharedUdpManager.js, companion/package.json, companion/test/Service/SharedUdpManager.test.js, yarn.lock
=> feat: shared udp listener #2399

docs/4_secondary_admin_controls/expressions/functions.md, shared-lib/lib/Expression/ExpressionFunctions.js, shared-lib/test/expressions-functions.test.js
To go with the split one requested in #2559
=> feat: Add expression array join function

webui/src/App.scss, webui/src/Buttons/ButtonGridZoomSlider.tsx, webui/src/Connections/ConnectionList.tsx, webui/src/Layout/Header.tsx, webui/src/Triggers/index.tsx, webui/src/scss/_instances.scss, webui/src/scss/_layout.scss, webui/src/scss/_variables.scss
Some fixes after coreui update, and some other general ui tweaks
=> fix: various UI tweaks and cleanup

webui/src/Components/VariablesTable.tsx, webui/src/Variables/index.tsx
Solves https://github.com/bitfocus/companion/issues/2852
Cleans up variable buttons similar to https://github.com/bitfocus/companion/pull/3015
=> fix: variables table display

webui/src/Components/VariablesTable.tsx, webui/src/Helpers/CollapseHelper.tsx
- Added separate copy actions for variable names and variable values
- Added `More` and `Less` actions to variable values where value length > 100 chars
Note: My first time working in React - may have done things in a particularly clunky way.
=> feat: collapsible variable table values

DEVELOPER.md
I have a few ideas I want to try developing in Companion and found that the DEVELOPER.md file seemed to be out of date. I hope this PR makes sense, and this is the right way to make a contribution to the project.
* Update the link to module development wiki page (it’s moved)
* Add a link to companion development
* Add  TL;DR section with the key points I need to remember when I come back to this project after working on others
=> chore: Improve instructions in DEVELOPER.md

webui/src/Controls/ButtonStyleConfig.tsx
Otherwise it seems like you can **never** use expressions here IMHO.
=> More positively nudge people to expression mode for buttons

docs/4_secondary_admin_controls/expressions/operators.md
Resolves issue #3477 (adds missing documentation)
=> Document binary exponentiation operator

launcher/main.js, launcher/window.css, launcher/window.html, launcher/window.js
=> feat: warn about upcoming incompatible macos version #3581

companion/lib/Internal/BuildingBlocks.ts, companion/lib/Internal/Controller.ts, companion/lib/Internal/Controls.ts, companion/lib/Registry.ts
closes #184
Example usage:
While this is 'wordier' than something more native like is proposed in #184, this gives more flexibility in what is looped and how.
=> feat: add while loop action
