bitfocus/companion

lib/instance/watchout_production/watchout_production.js, public/action.js, public/instance.js
Module and Action options can be validated during input with regex. You have to add "regex"-attribute to the action. When using backslash in the regex the backslashes have to be backslashed themself (double backslash). In the input field text not matching the regex gets colored red otherwise black.
=> Support for option validation with RegEx

lib/instance.js
Better than just using the parent folder name.
=> Use of "main" property of package.json for requiring a module

documentation/raspberrypi.md
libudev-dev and libusb-1.0-0-dev are needed for successful updating core with yarn and thus added to the documentation.
=> Added needed packages for raspi-builts

lib/instance.js
Bypasses the 'Bitfocus Companion' module from being added to modules_name array and therefore searchable in 'Add by search' Interface tab.
Tested.  Properly inhibits the module from 'Add by search' and did not see any errors in the normal execution or background load of the module/instance.
=> Issue 430 Patch

lib/feedback.js
#487 
Didn't want to merge this without a 2nd set of eyes looking at the overall issue.
=> Prevent 'feedback_instance_check' from executing with an empty instance

lib/osc.js
Along side pressing the button, this adds /style/bgcolor, /style/color and /style/text...
Pretty simple really, but I needed for an event so that QLab could update button labels based on very specific things. It could be argued this should be done as feedback on the OSC module, but I figured this was simpler.
=> Add ability to control button style with osc.

lib/feedback.js
Allows for feedback definitions to include a 'callback' function to process feedback as an alternate to using the feedbacks(...) function in the module.
Usage sample to follow in videohub update.
=> Minor: Add feedback definition callback

public/action.js, public/feedback.js, public/release_action.js
Two new controls available for actions and feedbacks:
A checkbox with a boolean value of `true` when checked and `false` when unchecked. The `default` property must be a boolean.
The value returned will be a boolean.
```
{
type: 'checkbox',
label: 'Invert',
id: 'invert'
tooltip: 'Inverts the layer',
default: false
}
```
Creates a [number input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) element which will only accept integers between `min` and `max` (inclusive). The `default` property must be a number (or `""` if not required). If the `required` property is `true` then the field can't be left empty.
If the `range` property is `true` then a [range input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) will also be created. Adding a range …
=> New action controls (checkbox and number/range input)

lib/rest.js
`system.on('rest_get')` can set additional headers and client connection options. Make those same options available to `system.on('rest')` for the POST method.
=> Allow REST POST to set headers and connection options

public/action.js, public/feedback.js, public/instance.js, public/release_action.js
Two new controls available for instance configs:
A checkbox with a boolean value of `true` when checked and `false` when unchecked. The `default` property must be a boolean.
The value returned will be a boolean.
```
{
type: 'checkbox',
label: 'HTTPS Connection',
id: 'https',
tooltip: 'Whether the connection is made over HTTPS',
default: false
}
```
Creates a [number input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) element which will only accept integers between min and max (inclusive). The `default` property must be a number (or `""` if not required). If the `required` property is `true` then the field can't be left empty.
The value returned will always be a number (example: `50`, not `"50"`), unless the field isn't required and was left empty, in which case …
=> New instance config controls (checkbox and number input) 

lib/udp.js
UDP/Datagram sockets (https://nodejs.org/api/dgram.html#dgram_event_message) use the `message` event when responding to a sent UDP packet and not a `data` event. Currently it's not possible to receive a response to a sent UDP packet.
I left it to re-emit the event as `data` to remain consistent with [tcp.js](https://github.com/bitfocus/companion/blob/master/lib/tcp.js#L119)'s event.
=> Fix: Listen for UDP 'message' event.

public/action.js, public/feedback.js, public/release_action.js
The "number" input type could fail and trigger browser Javascript errors, preventing the action or feedback from being created.
=> Patch: "number" input type could fail for new values.

lib/feedback.js, lib/instance_skel.js
addUpgradeScript does not currently support release_actions or feedback, meaning it is functionally broken.  These should be the necessary fixes, however, I have not had an opportunity to test.  Someone else may be able to get to that before I can and this can be merged once that is done.
=> Minor: add release_action and feedback support to addUpgradeScript

public/tablet.html
Requested by: https://github.com/bitfocus/companion/pull/806#issuecomment-528705414
Adds a maximum limit of 8 buttons wide (like an *Elgato Stream Deck XL*). 
**Large Screen Example:**
=> Added 8 buttons as maximum per width on tablet.html (master)

public/index.html, public/instance.js
A small tweak to move the apply changes button to above the list of dynamic variables.
Some devices (eg all ATEM) have over 100 variables, so having to scroll past those to save config changes is confusing and annoying.
After:
=> fix: move apply changes button in device configuration page

lib/feedback.js
Feedback wasn't updating for the button while editing the list in the ui. In each of adding, removing or editing the style would stay in the previous state.
This was especially bad when removing a feedback, as the style it defined would be remembered, and would persist until restart.
It will now trigger an update to make the button always be following the rules as shown in the ui.
=> fix: feedback not updating on creation or deletion

lib/server_http.js, package.json, public/bank.js, public/index.css, public/index.html
This adds autocomplete for variables to the button text field using the "[tributejs](https://github.com/zurb/tribute)" package.
Preview:
Summary:
- opens list of variables after entering `$(`
- list is filtered during typing
- use suggestions with `Enter`or by clicking on the item in the list
=> Minor: Add autocomplete for variables

lib/elgato_dm.js
This should fix the latest windows error mentioned in #836 
My development 1.4.0 branch seems to have newer node libraries than a bare 1.4.0 build.
linux needs the first patch to run with newer libraries, this one checks if the function exists first.
That function is available only in newer libraries that need it.
=> Check if HID function is available before using.

public/action.js, public/feedback.js, public/release_action.js
This will let modules use smaller steps on number inputs, if it make sense for that device.
(eg https://github.com/bitfocus/companion-module-atem/issues/34)
=> minor: Allow specifying step for numeric ui inputs

lib/instance.js, lib/loadsave.js, public/instance.js
Currently when adding a new instance, the user is presented with all products supported by the module (defined in package.json) and they choose a specific product to add.  However, this product selection is not being captured anywhere that I can see (only the instance type is emitted and stored in the instance config).  To illustrate, the `panasonic-ptz` module include many products:
but regardless of which of the products is selected, the module is always handed the following config:
```js
{
config: {
instance_type: 'panasonic-ptz',
label: 'Panasonic-PTZ'
}
}
```
This PR modifies the client to send both the instance type and product in the `instance_add` event and updates the server to include the product in the instance config stored in the DB.  This allows modules to customize the …
=> Store the project selected by the user in the instance config

lib/feedback.js, lib/instance_skel.js
A couple of bugs here with the upgrade config scripts.
1) No feedback was being passed into the scripts, as feedback properties are named differently to actions, and the loop to find them was using the wrong name. 
1) Every restart of companion was running the same scripts over again, as the change to _configIdx was not explicitly being saved
=> fix: upgradeConfig run at every startup. run with no feedbacks

lib/action.js
This is part of the fix for #596 and friends.
There is another patch for the submodule bitfocus-companion.
Fixed a potential (small) memory creep.
=> Issue #596 Prevent stale page button graphics

lib/device.js
Allow button graphics update without drawing on the new page.
Fixes #596
=> Button gfx timing adjust

lib/action.js
During my last round of testing for stale button images, I had the magic 'page' buttons responding on button release instead of press. It works, but not how you'd expect.
This restores the action to button press.
=> Fix page button oops

lib/action.js
the code was almost right, but the return was inside a callback, and needed to be bubbled up a layer
=> fix: latch button fires down action on second press

.github/workflows/nodejs.yml
This is a more durable fix for the windows build failures. This should ensure that any native dependency building can be done on windows when needed.
Example reproduction showing the pass and failure of building node-hid without using prebuilds: https://github.com/Julusian/test/runs/453623106?check_suite_focus=true
The builds in this project are now passing due to prebuilds of node-hid being published, but it is possible something else may try using node-gyp and fail later.
This was caused by node-gyp (used to build native dependencies) doesnt support the version of visual studio used by the github-actions windows image. This is fixed in node-gyp 5, but node8 is stuck on 3.8
=> fix: github actions unable to build native dependencies on windows

.gitignore, lib/instance_skel.d.ts, lib/instance_skel_types.d.ts
This moves the typescript definitions used by the atem module into core. I really should have done this a while ago, but there was no need to as only the atem module consumed them.
It will have no impact on any other module.
These have been left to stabilise for a few months, so should be pretty accurate but there could still be some small errors.
=> Minor: Add module typescript definitions

lib/instance_skel.d.ts, lib/instance_skel.js
Saw that there was a setVariable but no getVariable, and other modules just went around the issue by managing their own copy of the dynamic variable states. So I thought why not.
=> Added getVariable wrapper to instance_skel

public/action.js, public/index.css
Improves the positioning and sizing of the number range/spinner controls when viewed on smaller screens.
Also removes the default horizontal padding on the number range control, so that 0% and 100% actually reflect the edges of the control.
=> Fix positioning and sizing of number range/spinner controls for smaller screens

public/instance.js
Added the module help button to the instance config page.
Rationale: The help document may contain instructions on how to configure a module. This makes that document available without having to flip back and forth between the Instances tab and an instance's Config tab.
=> Minor: Added module help button to the instance config page

package.json, yarn.lock
Fixes the really slow draw speed for the xl on windows. (https://www.facebook.com/groups/companion/permalink/2537087016509633/)
For those interested, the built jpegturbo module was depending on a runtime library that is used by a lot of software. So the library was for some being installed by some other software, which explains why this hasnt been noticed before now. The fix was to rebuild the jpegturbo to not have a dependency on that library.
=> Patch: update jpegturbo

public/preset.js
Clones the preset that's being dragged so it doesn't need to animate back to its starting position after being dropped. Fixes #1043
=> Patch: Clone the dragged preset to show it's being copied not moved.

package.json
package.json excludes `documentation/*` from the builds, which stops documentation/gettingstarted.md from rendering ([PR #1045](https://github.com/bitfocus/companion/pull/1045#issuecomment-604491356)).
This PR removes that exclusion. My local `npm run macdist` builds now include the files as expected.
=> Include documentation/* in the compiled builds. See PR #1045

public/feedback.js, public/release_action.js
Apparently when we converted action & release_action dropdown type to use select2 we forgot about feedback.
Tested.  Basically a copy/paste from actions.
=> Minor: convert feedback dropdowns to select2

lib/feedback.js, lib/instance_skel.d.ts, lib/instance_skel.js, lib/instance_skel_types.d.ts, lib/loadsave.js
This PR adds 2 callbacks to the feedback definitions:
- `subscribe`: allows the feedback to send a `SUBSCRIBE` or `NOTIFY` command if it must request to receive updates for the associated data; or a simple `GET` can be sent to warm up the data should the device not have a catch-up method for its feedback data
- `unsubscribe`: allows the feedback to send a, `UNSUBSCRIBE` command should update subscription be required and the device recommends unsubscribing when certain updates are no longer required
These callbacks are invoked via two methods in an instance:
1. Manually via direct calls (outlined below) in the instance class.
2. Automatic `subscribe` and `unsubscribe` firing based on events such as:
- New feedback (subscribe)
- Edit feedback (unsubscribe old; subscribe new)
- Delete …
=> Minor: add feedback hooks (subscribe, unsubscribe)

public/instance.js
This will display the text argument when using `status(STATUS_UNKNOWN,'Something');`.
Before, the text message would be discarded.
It is useful as a progress message: 'Connecting', 'Initializing', etc. aren't errors, but the module is also not in an OK state, either.
=> Display status text from UNKNOWN

lib/action.js, lib/feedback.js, lib/instance.js, lib/instance_skel.d.ts, lib/instance_skel.js, lib/instance_skel_types.d.ts, lib/loadsave.js, public/release_action.js
Related: https://github.com/bitfocus/companion/pull/1062
This PR adds 3 callbacks to the action definitions, identical to those already on feedback definitions to allow for similar use cases:
- `callback`: execute the action. Takes priority over the instance level `action()` handler if this exists
- `subscribe`: allows the action to send a `SUBSCRIBE` or `NOTIFY` command if it must request to receive updates for the associated data; or a simple `GET` can be sent to warm up the data should the device not have a catch-up method for its action data
- `unsubscribe`: allows the action to send a, `UNSUBSCRIBE` command should update subscription be required and the device recommends unsubscribing when certain updates are no longer required
Note: for these, actions and release_actions are being …
=> Minor: add actions callbacks to match feedbacks (callback, subscribe, unsubscribe)

public/tablet2.html
It was pointed out on Facebook that I had the behavior of the page up/down buttons reversed from that of an actual stream deck so I have fixed that to avoid confusion.
=> Correct behavior of tablet2.html page up/down buttons to match actual stream deck

lib/server_http.js, package.json
This seems to have fixed #567 for me.
This keeps the static resources needed by express outside of the asar, which have issues after Companion runs for about a week. Before fix I was able to consistently replicate the issue, and after this change cannot.
=> Admin Stops Working

public/index.html
Documentation for the listener was reversed compared to what was expected. There was also a mix of terms used. I changed it to the terms page and button as well as correcting the . to : in the example.
=> Corrected rosstalk listener documentation

lib/instance_skel.js
Fixes #1217 
`REGEX_FLOAT_OR_INT` should accept more than one digit after the decimal point
=> Patch: correct typo in REGEX_FLOAT_OR_INT: fixes #1217

public/tablet2.html
This deals with issue #1194 by reading in the user config on page load and reversing the behavior of the page up/down buttons if requested. The behavior change applied to both the virtual deck's page up/down buttons as well as the extra ones added by page title. The Mobile Button's settings section has been updated to identify the current paging behavior and state that it is controlled through Companion's main admin settings.
=> Fix for #1194 - enable page direction flipped setting

lib/action.js
Missing fix for last piece of #775.
Existing patches prevented multiple 'press' (down) events from running down actions, 
but missed the case of multiple 'release' (up) events.
This patch adds that case.
=> Prevent multiple up on latch buttons

.github/workflows/nodejs.yml, Dockerfile, LICENSE.md, lib/elgato_dm.js, package.json, tools/asar-repack.js, tools/upload_build.js, yarn.lock
This updates the version of electron used to v8. I tried v9, but it was having issues starting on mac (didnt investigate much), and v10 doesnt have prebuilds for various native libs yet making it a little painful to use. This puts the matching version of node on v12.13.0, but latest 12 should be compatible for headless use.
Along with this various other libs have been updated, more could be done but would require better testing as they will be jumping major version numbers. A few that look to be unused were removed.
I have tested this out on windows, mac and linux and it runs for me on all 3. My testing has mostly consisted of it runs, no modules report failing to run, some basic instances appear to work, and a streamdeck is detected and works.
It did take some fighting with sharp to get …
=> Major: update electron to v8 (node 12)

lib/graphics.js, lib/image.js, lib/satellite_protocol.js, lib/satellite_server.js, lib/telnet.js, lib/usb/common.js
Updated uses of the deprecated `new Buffer()` to the Node12 compliant functions `Buffer.from()` and `Buffer.alloc()`.
Changes made following the guidelines of Variant 1 of the NodeJS Buffer constructor deprecation guide  https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
=> Fix: Node12 Buffer Update

electron.js, lib/elgato_dm.js, window.js
Adds a small context-menu to the tray-icon, which is shown on right-click (existing behaviour on other clicks)
Since the screenshot, I also added a 'Launch GUI' option, which behaves the same as shown in the skeleton window
This is the easy part of #1274
=> Minor: Add context-menu to tray icon

public/instance.js
Adds #1319 
When `instance_variables[]` are programmatically removed the `#instanceConfigVariables` element should be hidden.
=> Patch: hide the dynamic variables section on empty table

lib/instance.js
This would change execution from loading the main module scripts at launch to a just-in-time load during a validation check at instance add/activation.  With over 200 modules now it doesn't seem necessary to load all module code into RAM at launch.  Though there aren't major benefits either, so the usefulness of a change like this needs review.
Pros:
- ~5MB less RAM use
- Shorter launch speeds.
The RAM drop was from 381MB to 376MB on Win, so a 1% drop or effectively nothing.  The shorter launch speeds were perceivable on Windows, especially since the skeleton will normally hang for a brief period on launch.  This hang goes away completely.
Cons:
- A module add/activate may fail where-as an error related to the module may have shown in the logs at launch instead
- Such an error won't crash …
=> Minor: Change module load to just-in-time

lib/bank.js, public/bank.js, public/index.css
Implementing feature requested in #1358
- adds a button next to the "Browse" image button to clear an existing image
- a confirmation dialog is displayed to confirm the removal action
- the button is disabled when instance button has no image
=> Minor: ability to clear button image

lib/bank.js
I was in the middle of doing some research and I encountered this error. I'm not certain if it's causing any issues, but I figured we should fix it anyway.
=> Patch: fixed reference to button config during page/bank config init

public/index.html
Title is pretty self explanatory. This is in reference to a thread on Slack (https://bitfocusio.slack.com/archives/CFG7HAN5N/p1611578947020100). I think I got everything changed that is needed. The web interface appears to be loading correctly with the buttons tab selected by default.
=> Changed buttons tab to be selected by default

Dockerfile
If --branch stable-2.1 is not added to the dockerfile, this branch simply downloads the latest master version, which is NOT 2.1. This PR fixes this by changing to
git clone --branch stable-2.1 https://github.com/bitfocus/companion.git
=> Stable 2.1 dockerfile should force download of branch 2.1

lib/instance.js
This pull request prevents an instance from being enabled if it is already running. An already running instance could have been enabled by a button action and it would create a second instance that could not be disabled.
=> Prevent an instance from being enabled if it is already running

lib/action.js
Allows `Unlatch?` option for `Abort actions on button` to also skip up-actions on non-latch buttons.
Provides feature requested in #1496
=> Add ability for non-latch button to abort up acts

lib/schedule/variable.js
This fixes a bug where variables with conditionals would never fire since it was looking for the currently changed variable only vs all the variables to make sure they matched.
=> Triggers: Fixes variable conditions

instance_skel.d.ts, instance_skel.js, instance_skel_types.d.ts, lib/feedback.js, lib/graphics.js, webui/src/Buttons/EditButton/ButtonStyleConfig.jsx, webui/src/Buttons/EditButton/FeedbackPanel.jsx, webui/src/scss/_button-edit.scss
Fixes #1543
Feedbacks are currently responsible for returning an object of the style properties that they should change. This means it is not easily possible to choose what properties a feedback will change.
With this change, feedbacks can state that they will instead return a boolean value (the existing flow is called advanced, as it is still useful for advanced feedbacks such as showing a generated png).
These 'boolean' feedbacks then have their styling effect managed by core. The ui can dynamically change the properties being set based on what the user selects.
(ui might want some attention to make it pretty, I have gone for functional and easy to implement.
This is a start towards some of the ideas in https://github.com/bitfocus/companion/issues/1205
=> feat: boolean feedbacks

webui/src/Buttons/Variables.jsx, webui/src/scss/_bank.scss, webui/src/scss/_instances.scss, webui/src/scss/_layout.scss, webui/src/scss/_log.scss, webui/src/scss/_presets.scss
Hi, I got kinda tired of the UI only using half of my screen and did this to make it scale out on bigger screens, it changes at 1900px wide, so would b very close to the same on smaller screens, with the only difference being a bit of padding/margin form buttons like the "back" in variables and presets. And the "streamdeck" analogue in the buttons tab scales uniformly instead of only in with after a certain size.
I would not call this perfect but for me at least it feels better than how it is currently, it's mostly the way the icon for what button you are editing that annoys me a bit with this change, with how it hangs all the way to the right, but I could not figure out how to hover it over the "browse" button.
Please take a look and feel free to change it if need be, but scaling on …
=> fix: improve UI scaling on bigger screens + minor tweeks

lib/db.js
This backports from [feat/registry](https://github.com/bitfocus/companion/tree/feat/registry) various updates to `lib/db`, including:
- ES6 refactor
- Disabling `db_save` in favor of a save interval and `dirty` flag
- Add an auto-recovery of `db.bak` if `db` is corrupt or missing
- Attempts to save a `db.corrupt` copy if corruption is detected
- Adds `fs` checks for both `db` and `db.bak` to support those operations
This class was fairly rigorously tested a ways back.  I ran a small collection of tests and the functionality seems to work as tested earlier.  Changes made in [22c1e4](https://github.com/bitfocus/companion/commit/22c14e9f37a9667296c795039be55c025fbca069#diff-69f9a48e7478eb5df50c35b61f5638a078f274a604fff85d69732c2651ef8b47) have been incorporated
=> backport: lib/db load, recovery, and save interval changes

instance_skel.d.ts, instance_skel.js, lib/bank.js, lib/variable.js, webui/src/ContextData.jsx
This lets us reduce the number of events a bit, as the changes get passed around in a single lump.
It also reduces the number of list iterations we do, and lets some invalidations be batched.
Also, I looked over all the regexps in use, and stripped a lot of them back to basic string operations as they are sufficient and will be more perfomant
=> feat: allow modules to batch variables updates

lib/usb/elgato-mini.js, lib/usb/elgato-xl.js
The standard lib/usb/elgato.js has a mechanism for retrying the `fillImage` call a couple of times before giving up on the USB device. This Pull Request applies that retry to the elgato-mini and elgato-xl.
The original retry logic was added as a result of a discussion on Issue https://github.com/bitfocus/companion/issues/313#issuecomment-524150012
In our use case, we had our Mini disconnect from its RPi4 when several image updates were made in quick succession. After running for a month now, we've seen debug logs where it would have disconnected before, but with the patched code it continues working just fine.
Note: I've tested with a Mini but not the XL since I don't have an XL but the code is otherwise identical.
=> feat: Implement fillImage retries for elgato-mini and elgator-xl

lib/usb/xkeys_products.js
My XK-16 Stick (ID 1049) was being detected as an XK-4 due to incorrect product IDs. I’ve verified the IDs from the ‘X-keys XK-16 XK-8 XK-4 Stick Data Report.htm‘ file in the [HID reports](https://xkeys.com/software/developer/developerhiddatareports.html).
=> Correct X-keys XK-4 and XK-16 product IDs

lib/server_emberplus.js, lib/userconfig.js, webui/src/UserConfig.jsx
As a follow-up to #1644, the Ember+ service was not setup to be enabled via the settings page.  This adds that functionality.  Since the in place upgrade was designed to run once, this will disable the module for beta users since the merge on June 29, but will react appropriately for upgrades after a public release.
=> feat: ember+ service control

lib/device.js, lib/elgato_dm.js, lib/usb.js, lib/usb/common.js, lib/usb/handler.js, lib/usb/util.js, webui/src/Buttons/ButtonGrid.jsx, webui/src/Surfaces.jsx, webui/src/scss/_button-grid.scss
Replaces #1643
New config fields have been added to the surfaces, to allow for them to be positioned in the grid.
The implementation is done generically. I have tested it with a 15 key, and it should work for a mini or a satellite device
=> feat: streamdeck offset

lib/rest.js
Adding these HTTP methods as some REST APIs rely on them (for example Airtable) and can't be used properly with the methods missing.
This is used in https://github.com/bitfocus/companion-module-generic-http/pull/11
=> feat: Add http methods PATCH and DELETE to REST client

app.js
When the `DEVELOPER` flag is set, only set a default value for
`DEBUG` when one has not already been set.
Resolves #1784
Signed-off-by: Johnny Estilles <johnny@estilles.com>
=> feat: add ability to set custom DEBUG when DEVELOPER flag is set

webui/src/Buttons/EditButton/ButtonStyleConfig.jsx
This change reduces the minimum image sizes from 72x58 to 36x36.
Existing code already handles smaller images will. Images smaller
than 72x58 (down to 36x36) will be displayed as-is, without
resizing or padding.
Resolves #1774
Signed-off-by: Johnny Estilles <johnny@estilles.com>
=> feat(webui): reduce minimum image size to 36x36

instance_skel_types.d.ts, lib/instance.js, webui/src/Instances/InstanceEditPanel.jsx, webui/src/util.jsx
Conditionally display configuration fields based on the value(s) of other configuration fields.
A optional option `isVisible` can be assigned a function which receives the current `instanceConfig` to determine visibilty returning a Boolean. For backwards compatibility, if `isVisible` is not present the config field will always be displayed.
In the example below:
- the `version` field is always displayed
- the `community` field is only displayed when `version` is `v1` or `v2c` 
- the `engineID` field is only displayed when `version` is `v3`
```JavaScript
{
type: 'dropdown',
id: 'version',
label: 'SNMP Version',
width: 6,
choices: [
{ id: 'v1', label: 'SNMP v1' },
{ id: 'v2c', label: 'SNMP v2c' },
{ id: 'v3', label: 'SNMP v3' },
],
default: 'v1',
require: true,
},
{
type: 'textinput',
id: …
```
=> feat: add conditional config field display

package.json, yarn.lock
Fixes discrepancy between module name in manifest and repo name
Signed-off-by: Johnny Estilles <johnny@estilles.com>
=> module: Upgraded tesmart-hdmimatrix v1.0.1

tools/verify-module-build.mjs
I noticed modules do not load if the name on the manifest doesn't match the name of the repository/folder. (e.g. bitfocus/companion-module-tesmart-hdmimatrix#2)
This PR adds this check to the `verify-module-build.js` script.
Signed-off-by: Johnny Estilles <johnny@estilles.com>
=> chore(tools): check manifest/module names match

webui/src/Buttons/ButtonGrid.jsx
I've been asked so many times about a faster way to copy, paste, and move buttons that I wanted to add a little bit to the UI to tell people about it.
I just added `You can also use common key commands such as copy, paste, and cut to move buttons around. You can even press the delete or backspace key with any button highlighted to delete it.` to the current `<CAlert>` on the buttons page.
=> Added info about key commands to buttons page

instance_skel.js, instance_skel_types.d.ts, lib/instance.js, lib/resources/util.js, webui/src/Buttons/ButtonGrid.jsx, webui/src/Buttons/EditButton/ActionsPanel.jsx, webui/src/Buttons/EditButton/FeedbackPanel.jsx, webui/src/Buttons/EditButton/Table.jsx, webui/src/Instances/InstanceEditPanel.jsx
This is the next phase of my "conditional visibility" project. This PR includes:
- A slight refactoring of the `isVisible` implementation for config fields.
In the original implementation the `isVisible` property was overwritten with a serialized copy of the function. I wasn't happy with that, so instead I now add and `isVisibleFn` property which is the serialized copy of `isVisible`.
- Add `isVisible` to action options
- Add `isVisible` to feedback options
Because instance configs are slightly different from actions/feedbacks under the hood, this implementation is slightly different than the visibility implementation for config fields, but it is functionally equivalent for all intents and purposes.
The `isVisible` function receives a copy of the action state. The function then returns a …
=> Add `isVisibile` to action/feedback options

app.js, lib/elgato_dm.js, lib/elgato_emulator_device.js, lib/elgato_plugin_device.js, lib/elgato_plugin_server.js, lib/userconfig.js, webui/src/UserConfig.jsx
This should resolve some common issues from users who try the elgato plugin instead of native streamdeck support. eg #1795
The plugin api is now disabled by default. It has a userconfig field to enable it, and doing so will stop companion attempting to connect to streamdecks by itself.
So users will have to explicitly choose which way they want it to work.
There are still some edge cases where the two can fight, but this should solve the bulk of the cases and will resolve some of the issues observed at startup once it has already been setup.
I don't know how we can do this without blanket disabling the plugin for everyone, hopefully we are ok with that being done.
This can also be used to disable streamdeck loading #1771
=> feat: config field to enable the elgato plugin instead of scanning for local devices

.dockerignore, Dockerfile
This PR does the following:
1. It adds a healthcheck to the Dockerfile so that the container is marked as healthy/unhealthy. This is useful when running it as a swarm service so that it gets automatically restarted.
2. Expose the Satellite API port. As per Docker best practices, all open ports should be documented in the Dockerfile so that they are available for discovery to other tools and by other users
3. Minor cleanups to the `.dockerignore` file
=> feat: Add healthcheck and expose Satellite API port in Dockerfile

app.js, lib/server_http.js, lib/userconfig.js, webui/src/App.jsx, webui/src/App.scss, webui/src/ContextData.jsx, webui/src/Layout/Sidebar.jsx, webui/src/Wizard/ApplyStep.jsx, webui/src/Wizard/BeginStep.jsx, webui/src/Wizard/FinishStep.jsx, webui/src/Wizard/PasswordStep.jsx, webui/src/Wizard/ServicesStep.jsx, webui/src/Wizard/SurfacesStep.jsx, webui/src/Wizard/index.jsx, webui/src/scss/_wizard.scss
This feature adds a one-time configuration wizard as a modal popup for new installs and upgrades.  If it detects the lack of a `userconfig` setting called `v22_wizard` it will run and if the wizard is successfully completed or canceled out that setting is set to `true`.  A button has been added to the sidebar to manually launch the wizard.  It is non-destructive, meaning there is a confirmation step before it applies changes and can be canceled up to that point.
Simple welcome step indicates new and upgrade users should step through and review the settings.
Provides plain language on if the Elgato Plugin should be enabled or not, as well as the option for X-keys support.
Provides enable checkboxes for all of the listeners and displays dependent settings for the enabled settings.
Provides …
=> major: Add first-run configuration wizard

app.js, electron.js, lib/loadsave.js, webui/src/LogPanel.jsx
Adds "Show config folder" to the tray menu and "Export support bundle" to the log tab.
Minor change to headless that `companion.log` writes to the config directory instead of executable path so it can be included in the export.
=> feat: add support export and show config folder

webui/src/Buttons/EditButton/ActionsPanel.jsx, webui/src/Buttons/EditButton/AddModal.jsx, webui/src/Buttons/EditButton/FeedbackPanel.jsx, webui/src/Triggers/EditModal.jsx, webui/src/scss/_button-edit.scss
Closes #89
A browse button has been added next to each of the add dropdowns
This button opens a modal which lists all of the available actions/feedbacks, grouped by device. The devices are collapsible, making it possible to look through the items more easily.
There is a search box provided, which will filter the actions/feedbacks shown. When 'Add' is clicked it will add one of that immediately. It can be clicked multiple times to add multiple
Finally, the dropdown has been changed to show only the recently used entries. Once some input is provided it switches to searching all of the actions/feedbacks as before.
=> feat: browse and bulk add actions/feedbacks to button

Dockerfile, module-dev-docker-entrypoint.sh
Automatically install dependencies of local modules in docker. This also caches the dependencies so they will only be installed once. To enable this behaviour one should mount the local dev folder when running the container, example:
```bash
docker build . -t companion:dev # just once
docker run -it --rm -v $PWD/module-local-dev:/app/module-local-dev companion:dev
```
If no volumes are mounted as above, everything stays the same.
=> Install dependencies of local dev modules in Docker

tcp.js, telnet.js, udp.js
Various modules have forgotten to add error handlers to the udp/tcp wrappers we provide. This means that when they throw an error it will either crash companion or trigger the blocking error dialog.
To help mitigate this, we could add a check like this to log if a socket has been created and has no error handler setup.
I havent tested this yet.
Do all module devs run the 'dev' versions of commands? I know one who doesn't becuase the console is too noisy with internal logging. We might want to look at reducing the logging at the same time, or adding a 'module-dev' level of logging.
=> feat: report client wrappers which do not have an error handler

instance_skel.js, instance_skel_types.d.ts, lib/action.js, lib/feedback.js, package.json, webui/src/Buttons/EditButton/ActionsPanel.jsx, webui/src/Buttons/EditButton/FeedbackPanel.jsx, webui/src/Buttons/EditButton/index.jsx, webui/src/Triggers/EditModal.jsx, yarn.lock
This lets modules define a `learn` callback for actions and feedbacks to help users fill in the properties.
The idea is that instead of having to define the values inside of companion, you can set it up on the device and press learn to populate the current values into the action or feedback.
The methods take the same data as supplied to subscribe and unsubscribe, and the method is expected to return the new options object. Undefined/null is also valid if the method wishes to 'reject' the call.
For example, I have tested this with the `internal: Check variable value` feedback, so that it will populate the `Value` with the current value of the variable.
The bmd-atem module will benefit from this, as some of the supersource layouts are hard to define inside companion without a lot of trial …
=> feat: learn button for actions and feedbacks

lib/Controls/Button/Base.js, lib/Controls/Controller.js, webui/src/Buttons/EditButton/ActionsPanel.jsx, webui/src/Buttons/EditButton/CollapseHelper.jsx, webui/src/Buttons/EditButton/FeedbackPanel.jsx, webui/src/Buttons/EditButton/index.jsx, webui/src/Triggers/EditModal.jsx, webui/src/scss/_button-edit.scss, webui/src/scss/_common.scss
* actions and feedbacks can be collapsed/expanded to reduce screen usage
* actions and feedbacks can be duplicated
* actions can be dragged between sets (eg between down and up)
=> button editor improvements

instance_skel.js, lib/action.js, lib/bank.js, lib/device.js, lib/instance.js, lib/loadsave.js, lib/satellite/satellite_device.js, lib/satellite/satellite_server.js, lib/usb/loupedeck-live.js, webui/src/Buttons/EditButton/ButtonStyleConfig.jsx, webui/src/Buttons/EditButton/index.jsx
Follow up to #2110.
Programming for the encoders on the loupedeck-live is confusing due to how they are split across two buttons. There is also a bug which is easy to hit, where turning left sometimes doesnt fire without turning right once first. I suspect something to do with wanting to reject up events if there wasnt a recent down event?
This adds a minimal/simple way for the user to mark a button as being an encoder, and presenting 4 groups of actions:
* press/latch
* release/unlatch
* rotate left
* rotate right
I am unsure if this should be done as its own mode like this, or if it should be done as a checkbox/button next to the latching option, to show the extra fields. 
A mode like this feels simpler/cleaner, but it could cause frustration, as switching a button to an encoder does …
=> feat: better encoders support for loupdeck-live

Dockerfile
The plugin for the Elgato StreamDeck software connects through WebSocket on port 28492. The Dockerfile should expose the port.
=> chore(docker): expose WebSocket port for Elgato Plugin

lib/Data/Metrics.js, lib/Data/Upgrades/v2tov3.js, lib/Internal/Surface.js, lib/Service/Satellite.js, lib/Surface/Controller.js, lib/Surface/Handler.js, lib/Surface/IP/ElgatoEmulator.js, lib/Surface/IP/ElgatoPlugin.js, lib/Surface/IP/Satellite.js, lib/Surface/USB/ElgatoStreamDeck.js, lib/Surface/USB/Infinitton.js, lib/Surface/USB/LoupedeckLive.js, lib/Surface/USB/XKeys.js, webui/src/Surfaces.jsx
Connecting a streamdeck locally provides an id of `20DL0123456`, but if connected via satellite this becomes `satellite-20DL0123456`.
This results in some inconsistent behaviour, as plugging a streamdeck into different satellite machines will give it the same settings, but plugging it in directly will get different settings.
This changes the ids to always look like `streamdeck:20DL0123456` (or similar for other surface types).
This could break surface config for existing surfaces, but it is doing a crude attempt to fix up some ids. I expect there to be some friction for users here, partially as we need to either not change satellite or coordinate it.
It is attempting to gracefully handle old actions which use surface ids, trying to reliably fix them will prove complex
=> feat: make surface ids unique

lib/Controls/ControlTypes/Button/Base.js, lib/Instance/Definitions.js, lib/Instance/Host.js, lib/Instance/Variable.js, lib/Instance/Wrapper.js, lib/Internal/ActionRecorder.js, lib/Internal/Bank.js, lib/Internal/CustomVariables.js, lib/Internal/Surface.js, lib/Internal/System.js, test/variables-parse.test.js
Partner to https://github.com/bitfocus/companion-module-base/pull/32/files, which combined will allow for feedback to use `parseVariablesInString` and be rechecked when the variables referenced change.
Additionally, the same tracking has been applied to button drawing, so that nesting of variables finally updates correctly, rather than just the top level variables
=> feat: better variable change tracking

webui/package.json, webui/src/Instances/AddInstance.jsx, webui/yarn.lock
A lot of people give up when they search for a product but can't find it in the list. Searching for things like `black magic`, or `artnet` currently returns no results, which is unexpected. 
This PR improves the search filtering so that it matches items, even if spaces or punctuation isn't quite right. 
Also, should this PR target the `beta`, `develop`, or `master` branch? I couldn't find any guidelines
=> feat: Improve module list search filtering

Dockerfile
Install libasound2 in the dockerfile which is required for some modules (ie Renewed Vision ProPresenter)
=> fix: dockerfile install libasound2

lib/Shared/Expression/ExpressionFunctions.js
Added an additional Expression Function for parsing of milliseconds to a timestamp, and to allow the `secondsToTimestamp` function to default to the current `HH:mm:ss` format so it's non-breaking, but if specified it can also format the time in just hours, minutes, seconds, or a combination.
The parsing follows similarly to the Simple Date Format, but not exactly, as there is some adjustments for user experience. For example, `ms` is allowed in place of `.S` for tenth of a second, and `hh` and `HH` both format it in hours not bound by 12 or 24 respectively.
If we wanted a Expression Function for strictly formating date/time then that should be a separate function that more closely follows the Simple Date Format.
Usecase:
In preparation for making the vMix module, among others, v3 …
=> feat: Expression timestamp types, and ms parsing

lib/Controls/ControlTypes/Triggers/Events/Timer.js, lib/Controls/ControlTypes/Triggers/Trigger.js, lib/Resources/EventDefinitions.js
Adding a sunrise and sunset trigger event with the option to set an offset of ±12h.
The event uses a modified version of [this function](https://gist.github.com/adam-carter-fms/a44a14c0a8cdacbbc38276f6d553e024#file-sunriseset-js-L12) to estimate the sunrise/sunset times for given coordinates, instead of an API in order to make it work offline.
Closes Issue #1993
=> Add sunrise/sunset trigger event

lib/Service/Satellite.js, lib/Surface/IP/Satellite.js
This PR adds Fontsize as optional streamed data to the Sattelite API.
I added a new Flag `FONTSIZE` for the `ADD-DEVICE` command, similar to the already existing `TEXT`, `COLOR`, ...
if this flag is set to true, the fontsize is passed on every `KEY-STATE` message.
If this gets merged, the wiki would need to be updated at two places:
- Messages to send -> Adding a satellite device -> Optional parameters:
`FONTSIZE` - true/false whether you want to be streamed button font size for display on the buttons (default false) 
- Messages to receive -> State change for key:
`FONTSIZE` Font size as an integer for the key. This is only sent for devices which were added where `FONTSIZE` was true
=> feat: Add fontsize to Satellite API

launcher/main.js, lib/Data/Paths.cjs, main.js
3.0.0-rc1 is still using the `develop` subdirectory, as there was no convenient time to change it back to the root level without losing the config for some users.
This resolves that by renaming the folder to v3.0, and creating a symlink called develop, so that it is properly named, but older builds will still be able to load the same db through the symlink (verified on linux, macos and windows).
With this it is expected that each major/minor release, we will update it to use a new folder matching the release name, so that users can more easily jump between versions without risking db 'corruption', or having to manage the db file themselves.
Additionally, this embraces this new layout and performs a few checks at startup, to warn the user if a different version of companion has been run …
=> feat: tidy config dirs, and show message box when switching between versions

lib/Data/ImportExport.js, webui/src/Buttons/ButtonGrid.jsx, webui/src/Components/ConfirmExportModal.jsx, webui/src/ImportExport/Export.jsx, webui/src/ImportExport/ExportFormat.jsx, webui/src/ImportExport/index.jsx, webui/src/Triggers/index.jsx
This makes the default export format be gzipped json.
In most places where an export is done, it is possible to export as uncompressed json.
This uncompressed format is formatted json, so closes #2198. 
Compressed closes #231. gzip was chosen due to it being natively supported by nodejs, so it should be performent and will avoid any dependency issues.
=> feat: import and export compressed configs

lib/Controls/Controller.js, lib/Data/ImportExport.js, lib/Graphics/Controller.js, lib/Graphics/Image.js, lib/Graphics/ImageWrapper.js, lib/Graphics/Preview.js, lib/Graphics/Renderer.js, lib/Instance/Definitions.js, lib/Service/Satellite.js, lib/Surface/Handler.js, lib/Surface/IP/ElgatoEmulator.js, lib/Surface/IP/ElgatoPlugin.js, lib/Surface/IP/Satellite.js, lib/Surface/USB/ElgatoStreamDeck.js, lib/Surface/USB/Infinitton.js, lib/Surface/USB/LoupedeckCt.js, lib/Surface/USB/LoupedeckLive.js, lib/Surface/USB/XKeys.js, lib/Surface/Util.js, webui/src/ButtonRenderCache.jsx, webui/src/Buttons/EditButton.jsx, webui/src/Buttons/Presets.jsx, webui/src/Components/ButtonPreview.jsx, webui/src/Constants.js, webui/src/Controls/OptionButtonPreview.jsx, webui/src/Emulator/Emulator.jsx, webui/src/ImportExport/Import/Page.jsx, webui/src/Surfaces.jsx
Groundwork for supporting a larger grid size in the emulator
Also reworks the button render streaming to do the base64 conversion on the backend.
=> feat: resizable emulator

lib/Data/UserConfig.js, lib/Service/Controller.js, lib/Service/VideohubPanel.js, lib/Surface/Controller.js, lib/Surface/IP/VideohubPanel.js, package.json, webui/src/Surfaces/EditModal.jsx, webui/src/UserConfig/VideohubServerConfig.jsx, webui/src/UserConfig/index.jsx, yarn.lock
Replaces https://github.com/bitfocus/companion-module-bmd-videohub-controlpanel
This provides a minimal videohub 'server' implementation, to allow control panels to be connectde and be used as a surface.
Because of the number of buttons on the panels, the last 8 buttons take up a second row on the following page. Once we can make the grid larger, this can be fixed up.
Should this instead split it so each row is on a separate page? Perhaps only occupying a space of 5x4 on each of those pages?
This has been tested with a single panel, there is no reason it shouldn't work just fine with more.
When a panel connects, its settings are modified (requiring the ability for companion to connect back to the panels on port 9991) to be a 40 source, 1 output setup with sequential button order that we …
=> feat: videohub panel server

lib/Data/Upgrades/v3tov4.js, lib/Data/UserConfig.js, lib/Resources/Util.js, lib/Surface/Controller.js, lib/Surface/Handler.js, lib/Surface/IP/ElgatoPlugin.js, lib/Surface/IP/Satellite.js, lib/Surface/USB/ElgatoStreamDeck.js, lib/Surface/USB/Infinitton.js, lib/Surface/USB/LoupedeckCt.js, lib/Surface/USB/LoupedeckLive.js, lib/Surface/USB/XKeys.js, lib/Surface/Util.js, webui/src/Surfaces/EditModal.jsx, webui/src/UserConfig/SurfacesConfig.jsx
Related: #409
Instead of rotating purely the bitmaps inside of each key, this makes it possible to rotate everything about the panel.
For example, a 15 key streamdeck normally occupied a 5x3 area in the grid and once rotated will now occupy a 3x5 area instead.
For backwards compatibility, the old rotation modes have not been removed, that can be done in a later release.
Additionally, xkeys has been reworked, so that it no longer needs to span multiple pages or do other mangling to fit the panels into the grid.
This is controlled by a setting, so that existing xkeys users can choose when to switch their configurations to the new layout.
I have only tested this with a XK-24 and a XK-12 (Jog&Shuttle)
With this new layout, rotation works as you would expect. It is also offered when using the …
=> feat: improved surface rotation

lib/Instance/Definitions.js
Closes https://github.com/bitfocus/companion-module-base/issues/53
=> fix: Don't crash if feedbacks options are missing from presets bitfocus/companion-module-base#53

assets/linux/companion_headless.sh
The companion_headless.sh script was not working when it was symlinked, this fixes that 😄
=> Fix companion_headless.sh to work with symlinks

webui/src/Controls/OptionsInputField.jsx, webui/src/scss/_button-edit.scss
This is a pretty small change, that I think will help users. I am not 100% sold on the look, if anyone has ideas on how to improve it please do say
A simple indicator to show that the input field supports variables. On hover it shows `Supports variables`. It is using the `useVariables` property to decide to show this, which matches how we decide whether to suggest variables while typing.
I am hoping that we can add more icons to both this field type and others over time to indicate support for other features that modules need to implement support for
=> feat: indiciate variables support on input field

lib/Data/ImportExport.js
Modules that did not have an `upgradeScripts` prior to v3.0 do not have a `lastUpgradeIndex` in the instance database. This resulted in the upgrade script starting point being `undefined` when importing or upgrading.
As a result, no actions or feedbacks were passed to the upgrade scripts but the index was updated afterwards as if they had run.
=> Add default for lastUpgradeIndex

lib/Surface/USB/LoupedeckLive.js
Fixes https://github.com/bitfocus/companion/issues/2645
fixed `#loupedeck` initialization in `SurfaceUSBLoupedeckLive` constructor  (`LoupedeckLive.js`)
=> bug: (2645) fix LoupedeckLive constructor #loupedeck initialization (2645)

lib/Controls/Controller.js, lib/Instance/Wrapper.js, lib/Shared/Model/Options.ts, package.json, webui/package.json, webui/src/Buttons/EditButton.tsx, webui/src/Components/LearnButton.tsx, webui/src/ContextData.tsx, webui/src/Controls/ActionSetEditor.tsx, webui/src/Controls/FeedbackEditor.tsx, webui/src/_Model/ActiveLearn.ts, webui/src/util.tsx, webui/yarn.lock, yarn.lock
Closes #2619
To achieve this, the backend is now keeping track of the ids of the actions/feedbacks which are currently executing a 'learn', and it will reject an attempt to run two for the same id in parallel.
The client subscribes to the list of currently running learn requests, and any currently running learn buttons are now disabled, and show a spinning icon to indicate them running.
I have written this using mobx, as I want to try and use this more for the ui as a better way to do focused reactivity. The current context approach is not granular enough, causing large re-renders for small unrelated changes, which using mobx should resolve. I intend to explore that rework in develop, but don't see the harm in adding it for new stuff to beta
=> feat: configurable learn timeout

docs/3_config/buttons.md, lib/Controls/Controller.js, lib/Data/ImportExport.js, lib/Data/Upgrades/v1tov2.js, lib/Graphics/Controller.js, lib/Internal/Controller.js, lib/Internal/Page.js, lib/Internal/Surface.js, lib/Page/Controller.js, lib/Page/Defaults.js, lib/Service/EmberPlus.js, lib/Shared/Model/PageModel.ts, lib/Surface/Group.js, lib/Surface/Handler.js, webui/src/Buttons/ButtonGridActions.tsx, webui/src/Buttons/ButtonGridHeader.tsx, webui/src/Buttons/ButtonGridPanel.tsx, webui/src/Buttons/EditPageProperties.tsx, webui/src/Buttons/Pages.tsx, webui/src/Buttons/PagesAddModal.tsx, webui/src/Buttons/index.tsx, webui/src/Controls/InternalInstanceFields.tsx, webui/src/Hooks/usePagesInfoSubscription.ts, webui/src/Hooks/useUserConfigSubscription.ts, webui/src/ImportExport/Import/Page.tsx, webui/src/TabletView/index.tsx
Support more or less than 99 pages.
Fresh companion installations will start with 1 page, it is intended that users add as many pages as they need. Existing installations are unchanged, to avoid risking impacting users without them expecting it.
There is a new 'pages' tab in the right panel, which lists the pages with links to jump to a page, as well as to insert/add a page (at any position), and remove any page.
When adding a page, a modal is shown, to allow easily adding multiple and to encourage giving each new page a name
If when removing a page, a surface ends up out of bounds, it will be pushed to be within the new page count.
* Some work should be done to make surfaces more sticky to pages when they are removed/reordered
* The actions/feedbacks should be improved to be able to …
=> feat: more than 99 pages #2003

launcher/package.json
Companion was missing the usage description needed to send AppleEvents to application. This PR adds that description.
=> fix: Add `NSAppleEventsUsageDescription`

webui/package.json, webui/src/App.scss, webui/src/Components/TextInputField.tsx, webui/src/Controls/ButtonStyleConfig.tsx, webui/src/scss/_controls.scss, yarn.lock
This replaces uses of https://github.com/zurb/tribute which looks like it might no longer be maintained, and is not very react friendly with some custom wrapping around react-select, which we already use for simple dropdown fields.
This makes the ui a bit more consistent, as it matches the look of elsewhere, and avoids the bug of #2344 by locking the dropdown to always be below the text field, and to always be the full width
It is possible that there are some unintentional quirks in this new implementation, as some of the features of react-select have to be bypassed, and some functionality you would expect from this kind of 'suggestion' input have to be implemented around what react-select offers.
But as a bonus of this, we have a bit more control over some of the behaviour, which …
=> feat: replace variable picker dropdown #2344

companion/lib/Service/Controller.js, companion/lib/Service/HttpApi.js, companion/lib/UI/Express.js, companion/test/Service/HttpApi.test.js
So far the express routes of the new http API have been pushed to the end of the routes of express app. This results in bug #2820 where the default catch all get requests and return index is served before the get of the api.
This PR changes the routing a little bit:
The api router is invoked with a base url from the app, so all urls are relative to the base url there. The router itself does not define a base url any more.
Legacy API routes and the new API routes are set up in one shared router. The router is added dynamically to the express app and can be swapped at runtime to make the logic consistent with the controller.
The new api routes are now parsed before the legacy routes.
The catch all 404 route for the api is not a part of the legacy or the new api routes any more but always at …
=> fix: routes precedence #2820

companion/lib/Instance/Definitions.js, shared-lib/lib/Model/Presets.ts, webui/src/Buttons/Presets.tsx
This, along with a PR to Companion Module Base (https://github.com/bitfocus/companion-module-base/pull/80), will allow for the use of a `text` type preset as described in https://github.com/bitfocus/companion/issues/2843, and while not a full rework of the preset structure as suggested in that feature request the implementation of a text type does allow for modules to start utilizing it while consideration/changes to the preset structure take place at a later date.
The following is an example of some examples quickly placed in a module to show how they would be rendered when using something along the lines of
```js
{
category: 'Mix 1',
name: 'Test Header',
type: 'text',
text: 'Testing a text preset'
},
```
The `name` property takes the place of the header, while the `text` property will …
=> feat: Preset text type

tools/yarn.sh
The old/legacy modules have not been updated to be compatible with newer versions of Yarn.
This configures `modules-legacy` to use the an older Yarn version to manage the modules in the directory.
=> chore: force classic yarn for legacy modules

companion/lib/Resources/Util.js, companion/lib/Service/Satellite.js, companion/lib/Surface/IP/Satellite.js, webui/src/UserConfig/AdminPasswordConfig.tsx, webui/src/UserConfig/ArtnetConfig.tsx, webui/src/UserConfig/CompanionConfig.tsx, webui/src/UserConfig/EmberPlusConfig.tsx, webui/src/UserConfig/HttpsConfig.tsx, webui/src/UserConfig/OscConfig.tsx, webui/src/UserConfig/PinLockoutConfig.tsx, webui/src/UserConfig/RosstalkConfig.tsx, webui/src/UserConfig/TcpConfig.tsx, webui/src/UserConfig/UdpConfig.tsx
This PR:
- allows use of more than 32 buttons
- adds the text color if client requests colors (unfortunately the original API uses `color` for background color instead of `bgcolor`, so I use `textcolor` for text color instead of `color`)
- adds the option to read back colors in css rgb notation
- allows optionally to use button numbers in row/column format. The surface buttons start at 0/0 in that aspect, streamed button numbers are unchanged
API version is increased to 1.6.0  
as clients are required to actually parse parameter names and not only rely on positions, I consider the addition of textcolor parameter not a breaking change
This PR also has a bunch of completely unrelated formatting
=> Some updates to satellite API

docs/4_secondary_admin_controls/expressions/operators.md
"Modulous" -> "Modulus", "able" -> (removed as a word isn't needed at all)
=> chore: Correct typos in expressions operator documentation

docs/4_secondary_admin_controls/expressions/functions.md, shared-lib/lib/Expression/ExpressionFunctions.js, shared-lib/test/expressions-functions.test.js
Adds `timeOffset` and `timeDiff` Expression functions, as well as change the Expression Function documentation to create a `Time operations` section to group up these, and the previous time related functions.
`timeOffset` allows taking in a timestamp an offset, and optionally a 12 hour clock boolean, and outputting the time with that offset in the same format it came in with (eg, if hh:mm:ss is provided, then hh:mm:ss is returned, if seconds are omitted then likewise in the return value).
`timeDiff` compares 2 times, either in `hh:mm:ss` style format, or a Date Time String, eg `YYYY-MM-DDTHH:mm:ss.sssZ`, with the return value in seconds. This allows for easy creation of countdowns, formatting of the seconds can easily be done with the existing `msToTimestamp` Expression Function, and …
=> feat: Time Expression Functions

companion/lib/Internal/Controls.js, companion/lib/Internal/CustomVariables.js, companion/lib/Internal/Surface.js, companion/lib/Internal/Variables.js, docs/4_secondary_admin_controls/expressions/expressions.md, docs/4_secondary_admin_controls/expressions/operators.md, shared-lib/lib/Expression/ExpressionParse.js, shared-lib/lib/Expression/ExpressionResolve.js, shared-lib/lib/Expression/Plugins/Assignment.js, shared-lib/lib/Expression/Plugins/CompanionVariables.js, shared-lib/lib/Model/Options.ts, shared-lib/package.json, shared-lib/test/expressions-parse.test.js, shared-lib/test/expressions-resolver.test.js, webui/src/Components/TextInputField.tsx, webui/src/Controls/ButtonStyleConfig.tsx, webui/src/Controls/OptionsInputField.tsx, yarn.lock
This provides a bunch of improvements to expressions.
The most visible difference is that expression input fields are now displayed as multiline:
Expression input fields will now validate their expression in the ui, and will show as red when it failed to parse (execution is not tested)
Additionally, to make this more friendly, it includes some new syntax:
* Comments are now allowed. Same as javascript, both `//` and `/* ... */`
* Expressions can be multiline. Arbitrary line breaks are allowed, which allows for better formatting.
* `return` is a supported operation. Not exactly useful right now, but this can be nice to make an expression more readable in what the output value is
* It is possible to define intermediary variable inside an expression. Something such as `a = 1 ; return a + 2` …
=> feat: multiline expressions

assets/linux/50-companion-desktop.rules, assets/linux/50-companion-headless.rules, companion/lib/Data/UserConfig.js, companion/lib/Surface/Controller.js, companion/lib/Surface/USB/VECFootpedal.js, companion/package.json, docs/3_config/settings/surfaces.md, docs/7_surfaces/vec_footpedal.md, docs/structure.json, shared-lib/lib/Model/UserConfigModel.ts, webui/src/UserConfig/SurfacesConfig.tsx, webui/src/Wizard/ApplyStep.tsx, webui/src/Wizard/FinishStep.tsx, webui/src/Wizard/SurfacesStep.tsx, yarn.lock
=> feat: initial VEC Footpedal support

companion/lib/Service/Satellite.js, companion/lib/Surface/Controller.js, companion/lib/Surface/IP/Satellite.js
This adds support for 'variables' in the satellite api.
The satellite device can provide a basic description of any input (satellite to companion) and output (companion to satellite) variables it supports. These can then be mapped internally in the same way as used by #3012.  
This is needed for proper operation of https://github.com/bitfocus/companion-satellite/pull/147
This will allow for adding xkeys, shuttle and matching loupedeck-ct support in satellite, as these all update variables for portions which are not properly supported in companions grid view of surfaces.
=> feat: 'variables' in satellite api

companion/lib/Controls/ControlTypes/Triggers/Events/Timer.ts, companion/lib/Controls/ControlTypes/Triggers/Trigger.ts, companion/lib/Resources/EventDefinitions.ts, shared-lib/lib/Model/Options.ts, webui/package.json, webui/src/App.scss, webui/src/Controls/InternalInstanceFields.tsx, webui/src/scss/_react-date-picker.scss, yarn.lock
Closes https://github.com/bitfocus/companion/issues/1951
Adds a new trigger type, "Once on Specific Date/Time", which allows the user to specify a date and time that executes a trigger only once.
=> feat: add one-time event trigger

companion/lib/Data/ImportExport.ts, companion/lib/Data/UserConfig.ts, shared-lib/lib/Model/ImportExport.ts, shared-lib/lib/Model/UserConfigModel.ts, webui/src/Components/ConfirmExportModal.tsx, webui/src/ImportExport/Export.tsx, webui/src/UserConfig/CompanionConfig.tsx, webui/src/UserConfig/Components/UserConfigTextInputRow.tsx
This adds the a config field to customize export file names to aid with organization of config exports.
It partially addresses https://github.com/bitfocus/companion/issues/3075
=> feat: allow custom export file name

companion/lib/Controls/ControlTypes/Button/Normal.ts, companion/lib/Controls/ControlTypes/Triggers/Trigger.ts, companion/lib/Controls/Controller.ts, companion/lib/Controls/Fragments/FragmentActions.ts, companion/lib/Controls/IControlFragments.ts, shared-lib/lib/SocketIO.ts, webui/src/Controls/ActionSetEditor.tsx, webui/src/Controls/FeedbackEditor.tsx, webui/src/Services/Controls/ControlActionsService.ts, webui/src/scss/_button-edit.scss
This adds the possibility to change the connection of an action after creation.
A dropdown with all connections of the matching type is shown only if there are multiple connections of that type.
Upon change of the connection unsubscribe is called for the old instance and subscribe is called for the new instance.
Todo: improve positioning
=> feat: make connection of action changeable, closes #1498

.vscode/extensions.json, companion/lib/Controls/ControlBase.ts, companion/lib/Controls/ControlTypes/Button/Normal.ts, companion/lib/Controls/ControlTypes/PageDown.ts, companion/lib/Controls/ControlTypes/PageNumber.ts, companion/lib/Controls/ControlTypes/PageUp.ts, companion/lib/Controls/ControlTypes/Triggers/Trigger.ts, companion/lib/Controls/Controller.ts, companion/lib/Controls/Fragments/FragmentActions.ts, companion/lib/Controls/Fragments/FragmentFeedbacks.ts, companion/lib/Controls/IControlFragments.ts, companion/lib/Data/ImportExport.ts, companion/lib/Graphics/Image.ts, companion/lib/Resources/Util.ts, companion/lib/Service/HttpApi.ts, companion/lib/Surface/IP/Satellite.ts, companion/lib/Surface/USB/XKeys.ts, companion/lib/Variables/CustomVariable.ts, companion/lib/main.ts, companion/test/Service/SharedUdpManager.test.ts, docs/4_secondary_admin_controls/expressions/functions.md, webui/src/Components/AlignmentInputField.tsx, webui/src/Components/TextInputField.tsx, webui/src/Connections/ConnectionList.tsx, webui/src/ImportExport/index.tsx, webui/src/Wizard/GridStep.tsx
* Reformat and split Base64 encoded PNGs in YAML over multiple lines
* Change acceptable file extension for uploading to just .yaml instead of .companionconfig.yaml
* Two part file extensions don’t seem to work in all browsers, so YAML couldn't be loaded without manually selecting "all files"
Also:
* Recommend editorconfig and prettier VSCode extensions
* The config for both of theses linters is present, we should encourage people to use it
* Fix typos, mostly in comments e.g. `intiated` should be `initiated`
=> feat: YAML export-import improvements

companion/lib/Controls/Controller.ts, companion/lib/Controls/Fragments/FragmentFeedbackInstance.ts, companion/lib/Controls/Fragments/FragmentFeedbacks.ts, shared-lib/lib/SocketIO.ts, webui/src/Controls/FeedbackEditor.tsx, webui/src/Services/Controls/ControlFeedbacksService.ts
Same as with the actions this now adds the possibility to change the connection of a feedback.
Again the dropdown is only shown if there are multiple connections of the same type.
Again it is possible to also change to/from disabled connections.
=> feat: make connection of feedback changeable

webui/src/Connections/ConnectionList.tsx
This looks to resolve https://github.com/bitfocus/companion/issues/2816 by implementing the strategy outlined in the first [comment ](https://github.com/bitfocus/companion/issues/2816#issuecomment-2019266064).
Basically, this moves all statuses to icons (previously only OK was an icon, and the rest could be any amount of text determined by the module). This uses icons to consistently and cleanly get across the status state. More info can be found by hovering over the icons, which prints out the status level and additional messages from the module.
=> feat: standardize status to icons

companion/lib/ImportExport/Controller.ts
Fixes #3242.  I got bogged down where I was, so I was able to test this in Safari (as well as the more cross-platform Firefox and Chrome).
I believe this is a bugfix that could reasonably be taken in a point release (although I developed it against `main` and haven't checked whether it would backport).  I actually ran into this trying to avail myself of this using the current `.companionconfig` naming style I have for my own site backups when I make changes (in this case, after doing the `s/internal:custom_/custom:/g` change throughout my configuration), and it would be nice to be able to make use of this feature and not change my previous naming style to work around this.
=> fix: Specify the config export download filename in the modern way

companion/lib/ImportExport/Controller.ts
I was rereading the landed commit and noticed I wasn't escaping backslashes.  :neutral_face:  The effect of not doing so seems to be fairly minimal -- this is a "trusted" input from the user so they could only mess with themselves -- but still, worth getting it right.
=> fix: Also escape backslashes in the Content-Disposition legacy filename parameter

companion/lib/Variables/CustomVariable.ts, shared-lib/lib/SocketIO.ts, webui/src/Variables/CustomVariablesList.tsx, webui/src/scss/_instances.scss
For the most part this was driven by finding the UI that needed changing, then following the TypeScript breadcrumbs.  I mostly stomped around here.  :slightly_smiling_face:
My webdev knowledge is dated enough to not include CSS Grid beyond starting an MDN read , so I largely worked around it by shunting the collapsed description to its own line (`.variable-description` exists to sync with `.variable-style` in [`App.scss`](https://github.com/bitfocus/companion/blob/25912fab53986a5305e450507ce09f89776cad92/webui/src/App.scss#L133)), rather than trying to wedge it somewhere into the top line.  One could _argue_ for doing the table the way it's done for module variables which uses a table.  But I was trying to do the relatively least change I could to get something half-suitable.  (Honestly, …
=> feat: Allow custom variables' descriptions to be edited

companion/lib/Data/UserConfig.ts, companion/lib/Surface/Controller.ts, companion/lib/Surface/Handler.ts, companion/lib/Surface/Types.ts, companion/lib/Surface/USB/XKeys.ts, shared-lib/lib/Model/UserConfigModel.ts, webui/src/UserConfig/Sections/SurfacesConfig.tsx
This is a breaking change, removing support for the old xkeys compatibility layouts.
The new 'accurate' layouts have been the default since 3.2, so hopefully this won't impact many users
TBD whether this will happen soon or be put off until it becomes necessary
=> feat!: remove support for legacy xkeys layouts

companion/lib/Instance/ApiVersions.ts, companion/lib/Instance/Host.ts, companion/lib/Instance/NodePath.ts, companion/lib/Instance/Wrapper.ts, companion/package.json, shared-lib/lib/ModuleApiVersionCheck.ts, yarn.lock
Closes #3207
This enables the permissions model for modules running the module-api v1.12.0 and node22.
As such it is 'opt-in' per module, and so I do not think we need to class as a breaking change (although it may become 2.0.0, due to other changes coming soon to the api)
I have verified that these checks are also applied correctly when developing a module, so there shouldnt be any surprises when releasing a module.
Ideally we should also report these modules in the UI somewhere, but that can come later
=> feat: support nodejs permissions model

companion/lib/Service/BonjourDiscovery.ts
Requires https://github.com/bitfocus/companion-module-base/pull/133 as well.
This allows modules to filter by port number, for devices / software that have static communication ports.
=> feat: allow filtering bonjour queries by port

companion/lib/Surface/USB/ContourShuttle.ts
The button mappings work correctly on my ContourShuttlePro V1, so deleting the TODO:
~~~
// TODO(Someone with hardware): This mapping is guesswork and hasn't been tested
~~~
P.S. Please let me know if you'd prefer I report this in other ways than a PR!
=> Confirm mapping for ContourShuttlePro V1

webui/src/Components/CheckboxInputField.tsx
This is a workaround to fix an issue in Safari with the checkbox UI.
This is before, if the label text was multiline it would cause the checkbox to jump and be difficult to select: 
https://github.com/user-attachments/assets/6660180e-a9ef-4f2d-90e4-4f4834a5e592
After:
https://github.com/user-attachments/assets/4a1a9ff8-755e-456f-97e0-605f0567cd37
=> fix: checkbox option jumping in safari

webui/src/Surfaces/KnownSurfacesTable.tsx
(This idea could be applied to the current stable version too.)
Now that I've had a chance to play with the new Surfaces page, I believe that indentation would really help: Even though the "NO" column indicates groups, that column is easy to overlook. This PR indents members of a group under the group heading to make group membership clearer (especially for single-member groups).
=> Improve "visibility" of groups in the new surfaces page

webui/src/Layout/Header.tsx, webui/src/Layout/Sidebar.tsx, webui/src/scss/_layout.scss
~~I am not 100% certain on this, so throwing it here for any feedback.~~
Its always felt a bit weird/messy to have the version number so prominent on the top header bar. This moves it to the bottom of the sidebar:
For a stable build:
=> feat: move version number into sidebar

companion/lib/Data/Database.ts, companion/lib/Data/StoreBase.ts, companion/lib/Data/UserConfig.ts, companion/lib/ImportExport/Backups.ts, companion/lib/ImportExport/Controller.ts, companion/lib/ImportExport/Export.ts, companion/lib/ImportExport/Util.ts, companion/lib/Registry.ts, companion/package.json, shared-lib/lib/Model/UserConfigModel.ts, webui/src/Layout/Sidebar.tsx, webui/src/UserConfig/BackupConstants.ts, webui/src/UserConfig/BackupRuleEditor.tsx, webui/src/UserConfig/backups.tsx, webui/src/UserConfig/index.tsx, webui/src/routeTree.gen.ts, webui/src/routes/app/settings/backups.tsx, webui/src/routes/app/settings/backups/$ruleId.tsx, webui/src/routes/app/settings/backups/index.tsx, yarn.lock
closes #2961
This allows the user to define some auto-backup on interval
The idea is that the user can define different rules, into different paths on different intervals.  
One could be a daily one into dropbox keeping 90 days worth, another could be hourly elsewhere keeping the last 2.
This supports the usual export formats, and the 'raw database' format, which is a full sqlite db. For now that is the default, but if we get to a point where a normal export contains 'everything', then we could change the default format.
=> feat: improved backups control #2961

companion/lib/ImportExport/Controller.ts, docs/3_config/import-export/import.md, webui/src/ImportExport/Import/Full.tsx
This commit/PR implements the feature described in #3348
Note that although there may be some interdependencies between the import categories, it seems to me that resetting all is certain to break them when importing only a subset of all the categories, whereas leaving the unimported sections alone makes it likely that things won't break...  (The same argument goes for userconfig: since it currently isn't saved, it shouldn't be reset.)
=> Ability to import components without a full reset

webui/src/Buttons/EditButton/ButtonEditorTabs.tsx, webui/src/Buttons/EditButton/ControlActionStepTab.tsx, webui/src/Controls/Components/EntityCellControls.tsx, webui/src/Triggers/EventEditor.tsx
This could be considered a "fix" or a "feat"...
Although the difference is subtle, the change could be considered a first baby step to adding cut/copy/paste functionality to those items.
(Note, I might have preferred the unfilled icon, to make the difference more distinct, but that would involve loading the "regular" font, which we currently don't use.)
Current: (steps, actions, action containers, trigger events)
This PR:
Maybe better, but requires installing additional font:
=> Replace "copy" icon with "clone" icon for duplication

webui/src/Components/PNGInputField.tsx
(Note: I can post an issue if you prefer, or do so in the future -- this one just removes a minor though persistent annoyance so it didn't seem worth it.)
When the contents of a PNG file is updated, replacing the button image from the file of the same name doesn't always work, when using the PNG "folder" button:
Specifically,
1. Load a PNG file using the PNG "folder" button.
2. Stay on the Buttons page
3. Modify the PNG file. (Switching apps doesn't matter, just as long as "Bitfocus Companion - Admin" remains on the same page)
4. Try to update the button-image  using the PNG "folder" button and selecting the updated file (same name as before).
Moving to a different buttons page doesn't help, though moving to a different URL or restarting will solve the problem.
This commit fixes the …
=> fix: Edit-Button Load-PNG not loading updated files

companion/lib/Surface/Handler.ts
See issue  #3526 for details.
(Minor note: I would have preferred a Map to a Record for `this.#currentButtonPresses` but didn't change it from the original. Obviously, both ways work...)
Closes issue #3526
=> Fix issue #3526 - Button may remain pressed if it changes its offset

companion/lib/Surface/Controller.ts, companion/lib/Surface/USB/MiraboxStreamDock.ts
This contribution adds support for the MiraBox HSV293S.
Code taken from @andrzejl (https://github.com/bitfocus/companion-module-requests/issues/1494#issuecomment-3133545643), and modified to fit with the implementation on main. Modify the model for a StreamBox such that it exposes an iconRotation property. Modify offsetRotation() call to use this new property.
=> Add support for the MiraBox HSV293S.

companion/lib/main.ts, launcher-ui/src/Sections.tsx, launcher-ui/src/contexts/ConfigContext.tsx, launcher-ui/src/sections/Syslog.tsx, launcher-ui/src/types/config.ts, launcher/main.js
Add syslog configuration to the new launcher `Advanced Settings` window.
I would prefer to allow specifying the syslog server via hostname as well as IP; however when an invalid hostname is supplied, companion will crash when trying to write to the logs, and this is not caught by the `try/catch` block that sets up the syslog transport for winston.
When the `Local Hostname` field is empty, the system defaults to `os.hostname()`
Trigger restart debounce duration extended slightly to make it more tolerant of typing in the text fields.
=> feat: configure syslog from launcher

companion/lib/Surface/IP/ElgatoEmulator.ts
Remove nonsense tooltip from surfaces/emulator settings tab.
=> fix: remove nonsense tooltip

docs/4_secondary_admin_controls/expressions/functions.md, shared-lib/lib/Expression/ExpressionFunctions.ts, shared-lib/lib/__tests__/expressions-functions.test.ts
**The issue**
`secondsToTimestamp` prepends negative number with a minus sign while `msToTimestamp` dose not
**Other stuff**
add test for the representing the new functionality.
unified the path for timestamp generation in both the millisecond and seconds case 
**Questions**
I could add formatting for days as well to fix the note about more than 24 hours?
I could implement a non padding option, "h:mm:s" -> 1:05:30 ?
=> FIX: Negative value in msToTimestamp

companion/lib/Surface/Controller.ts, companion/lib/Surface/USB/MiraboxStreamDock.ts
This is a complementary PR to https://github.com/bitfocus/companion/pull/3590.
There seem to be multiple version of the HSV293S.
The unit I have is branded as a Soomfon XF-CN001, but the electronic board indicates HSV 293 S.
The main differences with the already HSV 293 S version are:
- Different vendor id / product ID
- Button display size is 85x85 pixels
- The packets are only 512 bytes instead of 1024 for other implemented devices.
It seems similar to other branded versions such as this one: https://gist.github.com/ZCube/430fab6039899eaa0e18367f60d36b3c (also with 512 bytes packet size)
This unit also only support push mode, and not button mode, which means that there's no "hold" functionality possible.
=> feat: Add support to alternative version of mirabox hsv293s

companion/lib/UI/Express.ts, webui/src/Connections/AddConnectionPanel.tsx, webui/src/Connections/ConnectionEdit/ConnectionEditPanel.tsx, webui/src/Connections/ConnectionList/ConnectionList.tsx, webui/src/Connections/index.tsx, webui/src/Layout/Sidebar.tsx, webui/src/Modules/ModuleManagePanel.tsx, webui/src/Modules/index.tsx, webui/src/routeTree.gen.ts, webui/src/routes/app/connections/$.tsx, webui/src/routes/app/connections/configured.tsx, webui/src/routes/app/connections/configured/$connectionId.tsx, webui/src/routes/app/connections/configured/add.tsx, webui/src/routes/app/connections/configured/index.tsx, webui/src/routes/app/connections/modules.tsx, webui/src/routes/app/connections/modules/$moduleId.tsx, webui/src/routes/app/connections/modules/index.tsx, webui/src/routes/app/index.tsx, webui/src/routes/app/modules.tsx, webui/vite.config.ts
A small reshuffle of the sidebar.
This will hopefully make this be both more visible when configuring connections, and will hopefully avoid it being confused in the future with other pages.  
It probably should have been placed here from the beginning, I think it was bad timing that resulted in it being at the root level. From memory, the modules was largely implemented in a different branch by the time the sidebar rework was done.
This is partly in preparation for surfaces becoming their own modules/plugins, as they will need their own page for managing versions, and the module naming may be used.  
By having these as subpages, they get the needed context.
=> feat: move modules in sidebar
